package com.daniluk.covid_19.utils

object FlagsCountries {
    val mapFlagsCountries = mapOf(
        "Andorra" to listOf("AD", "Андорра", "AND", "20"),
        "UAE"	to listOf("AE", "Объединённые Арабские Эмираты", "ARE", "784"),
        "Afghanistan" to listOf("AF", "Афганистан", "AFG", "4"),
        "Antigua and Barbuda" to listOf("AG", "Антигуа и Барбуда", "ATG", "28"),
        "Anguilla" to listOf("AI", "Ангилья", "AIA", "660"),
        "Albania" to listOf("AL", "Албания", "ALB", "8"),
        "Armenia" to listOf("AM", "Армения", "ARM", "51"),
        "Netherlands Antilles" to listOf("AN", "Нидерландские Антилы", "ANT", "530"),
        "Angola" to listOf("AO", "Ангола", "AGO", "24"),
        "Antarctica" to listOf("AQ", "Антарктида", "ATA", "10"),
        "Argentina" to listOf("AR", "Аргентина", "ARG", "32"),
        "American Samoa" to listOf("AS", "Американское Самоа", "ASM", "16"),
        "Austria" to listOf("AT", "Австрия", "AUT", "40"),
        "Australia" to listOf("AU", "Австралия", "AUS", "36"),
        "Aruba" to listOf("AW", "Аруба", "ABW", "533"),
        "Aland Islands" to  listOf("AX", "Эландские острова", "ALA", "248"),
        "Azerbaijan" to listOf("AZ", "Азербайджан", "AZE", "31"),
        "Bosnia-and-Herzegovina" to listOf("BA", "Босния и Герцеговина", "BIH", "70"),
        "Barbados" to listOf("BB", "Барбадос", "BRB", "52"),
        "Bangladesh" to listOf("BD", "Бангладеш", "BGD", "50"),
        "Belgium" to listOf("BE", "Бельгия", "BEL", "56"),
        "Burkina Faso" to listOf("BF", "Буркина Фасо", "BFA", "854"),
        "Bulgaria" to listOf("BG", "Болгария", "BGR", "100"),
        "Bahrain" to listOf("BH", "Бахрейн", "BHR", "48"),
        "Burundi" to listOf("BI", "Бурунди", "BDI", "108"),
        "Benin" to listOf("BJ", "Бенин", "BEN", "204"),
    "St-Barth" to listOf("BL", "Сен-Бартельми", "BLM", "652"),
    "Bermuda" to listOf("BM", "Бермуды", "BMU", "60"),
    "Brunei" to listOf("BN", "Бруней", "BRN", "96"),
    "Bolivia" to listOf("BO", "Боливия", "BOL", "68"),
    "Brazil" to listOf("BR", "Бразилия", "BRA", "76"),
    "Bahamas" to listOf("BS", "Багамы", "BHS", "44"),
    "Bhutan" to listOf("BT", "Бутан", "BTN", "64"),
    "Bouvet Island" to listOf("BV", "Остров Буве", "BVT", "74"),
    "Botswana" to listOf("BW", "Ботсвана", "BWA", "72"),
    "Belarus" to listOf("BY", "Беларусь", "BLR", "112"),
    "Belize" to listOf("BZ", "Белиз", "BLZ", "84"),
    "Canada" to listOf("CA", "Канада", "CAN", "124"),
    "Cocos (Keeling) Islands" to listOf("CC", "Кокосовые (Килинг) острова", "CCK", "166"),
    "Congo (Democratic Republic)" to listOf("CD", "Конго (Демократическая Республика)", "COD", "180"),
    "Central African Republic" to listOf("CF", "Центральноафриканская Республика", "CAF", "140"),
    "Congo" to listOf("CG", "Конго", "COG", "178"),
    "Switzerland" to listOf("CH", "Швейцария", "CHE", "756"),
    "Cote d’Ivoire" to listOf("CI", "Кот-д’Ивуар", "CIV", "384"),
    "Cook Islands" to listOf("CK", "Острова Кука", "COK", "184"),
    "Chile" to listOf("CL", "Чили", "CHL", "152"),
    "Cameroon" to listOf("CM", "Камерун", "CMR", "120"),
    "China" to listOf("CN", "Китай", "CHN", "156"),
    "Colombia" to listOf("CO", "Колумбия", "COL", "170"),
    "Costa Rica" to listOf("CR", "Коста-Рика", "CRI", "188"),
    "Cuba" to listOf("CU", "Куба", "CUB", "192"),
    "Cape Verde" to listOf("CV", "Cape Verde", "Кабо-Верде", "CPV", "132"),
    "Christmas Island" to listOf("CX", "Остров Рождества", "CXR", "162"),
    "Cyprus" to listOf("CY", "Кипр", "CYP", "196"),
    "Czech Republic" to listOf("CZ", "Чехия", "CZE", "203"),
    "Germany" to listOf("DE", "Германия", "DEU", "276"),
    "Djibouti" to listOf("DJ", "Джибути", "DJI", "262"),
    "Denmark" to listOf("DK", "Дания", "DNK", "208"),
    "Dominica" to listOf("DM", "Доминика", "DMA", "212"),
    "Dominican-Republic" to listOf("DOM", "Доминиканская Республика", "DOM", "214"),
    "Algeria" to listOf("DZ", "Алжир", "DZA", "12"),
    "Ecuador" to listOf("EC", "Эквадор", "ECU", "218"),
    "Estonia" to listOf("EE", "Эстония", "EST", "233"),
    "Egypt" to listOf("EG", "Египет", "EGY", "818"),
    "Western Sahara" to listOf("EH", "Западная Сахара", "ESH", "732"),
    "Eritrea" to listOf("ER", "Эритрея", "ERI", "232"),
    "Ceuta" to listOf("ES-CE", "Сеута", null, null),
    "Melilla" to listOf("ES-ML", "Мельлия", null, null),
    "Spain" to listOf("ES", "Испания", "ESP", "724"),
    "Ethiopia" to listOf("ET", "Эфиопия", "ETH", "231"),
    "European Union" to listOf("EU", "Евросоюз", null, null),
    "Finland" to listOf("FI", "Финляндия", "FIN", "246"),
    "Fiji" to listOf("FJ", "Фиджи", "FJI", "242"),
    "Falkland-Islands" to listOf("FK", "Фолклендские острова (Мальвинские)", "FLK", "238"),
    "Micronesia" to listOf("FM", "Микронезия", "FSM", "583"),
    "Faroe Islands" to listOf("FO", "Фарерские острова", "FRO", "234"),
    "France" to listOf("FR", "Франция", "FRA", "250"),
    "Gabon" to listOf("GA", "Габон", "GAB", "266"),
    "UK" to listOf("GB", "Великобритания", "GBR", "826"),
    "Grenada" to listOf("GD", "Гренада", "GRD", "308"),
    "Georgia" to listOf("GE", "Грузия", "GEO", "268"),
    "French-Guiana" to listOf("GF", "Французская Гвиана", "GUF", "254"),
    "Guernsey" to listOf("GG", "Гернси", "GGY", "831"),
    "Ghana" to listOf("GH", "Гана", "GHA", "288"),
    "Gibraltar" to listOf("GI", "Гибралтар", "GIB", "292"),
    "Greenland" to listOf("GL", "Гренландия", "GRL", "304"),
    "Gambia" to listOf("GM", "Гамбия", "GMB", "270"),
    "Guinea" to listOf("GN", "Гвинея", "GIN", "324"),
    "Guadeloupe" to listOf("GP", "Гваделупа", "GLP", "312"),
    "Equatorial-Guinea" to listOf("GQ", "Экваториальная Гвинея", "GNQ", "226"),
    "Greece" to listOf("GR", "Греция", "GRC", "300"),
    "South Georgia and the South Sandwich Islands" to listOf("GS", "Южная Джорджия и Южные Сандвичевы острова", "SGS", "239"),
    "Guatemala" to listOf("GT", "Гватемала", "GTM", "320"),
    "Guam" to listOf("GU", "Гуам", "GUM", "316"),
    "Guinea-Bissau" to listOf("GW", "Гвинея-Бисау", "GNB", "624"),
    "Guyana" to listOf("GY", "Гайана", "GUY", "328"),
    "Hong Kong" to listOf("HK", "Гонконг", "HKG", "344"),
    "Heard Island and McDonald Islands" to listOf("HM", "Остров Херд и острова Макдональд", "HMD", "334"),
    "Honduras" to listOf("HN", "Гондурас", "HND", "340"),
    "Croatia" to listOf("HR", "Хорватия", "HRV", "191"),
    "Haiti" to listOf("HT", "Гаити", "HTI", "332"),
    "Hungary" to listOf("HU", "Венгрия", "HUN", "348"),
    "Canary Islands" to listOf("IC", "Канарские острова", null, null),
    "Indonesia" to listOf("ID", "Индонезия", "IDN", "360"),
    "Ireland" to listOf("IE", "Ирландия", "IRL", "372"),
    "Israel" to listOf("IL", "Израиль", "ISR", "376"),
    "Isle-of-Man" to listOf("IM", "Остров Мэн", "IMN", "833"),
    "India" to listOf("IN", "Индия", "IND", "356"),
    "British Indian Ocean Territory" to listOf("IO", "Британская территория в Индийском океане", "IOT", "86"),
    "Iraq" to listOf("IQ", "Ирак", "IRQ", "368"),
    "Iran" to listOf("IR", "Иран", "IRN", "364"),
    "Iceland" to listOf("IS", "Исландия", "ISL", "352"),
    "Italy" to listOf("IT", "Италия", "ITA", "380"),
    "Jersey" to listOf("JE", "Джерси", "JEY", "832"),
    "Jamaica"  to listOf("JM", "Ямайка", "JAM", "388"),
    "Jordan" to listOf("JO", "Иордания", "JOR", "400"),
    "Japan" to listOf("JP", "Япония", "JPN", "392"),
    "Kenya" to listOf("KE", "Кения", "KEN", "404"),
    "Kyrgyzstan" to listOf("KG", "Киргизия", "KGZ", "417"),
    "Cambodia" to listOf("KH", "Камбоджа", "KHM", "116"),
    "Kiribati" to listOf("KI", "Кирибати", "KIR", "296"),
    "Comoros" to listOf("KM", "Коморы", "COM", "174"),
    "Saint-Kitts-and-Nevis" to listOf("KN", "Сент-Китс и Невис", "KNA", "659"),
    "Kosovo" to listOf("KOSOVO", "Косово", null, null),
    "North Korea" to listOf("KP", "Северная Корея", "PRK", "408"),
    "S-Korea" to listOf("KR", "Южная Корея", "KOR", "410"),
    "Kuwait" to listOf("KW", "Кувейт", "KWT", "414"),
    "Cayman Islands" to listOf("KY", "Острова Кайман", "CYM", "136"),
    "Kazakhstan" to listOf("KZ", "Казахстан", "KAZ", "398"),
    "Laos" to listOf("LA", "Лаос", "LAO", "418"),
    "Lebanon" to listOf("LB", "Ливан", "LBN", "422"),
    "Saint Lucia" to listOf("LC", "Сент-Люсия", "LCA", "662"),
    "Liechtenstein" to listOf("LI", "Лихтенштейн", "LIE", "438"),
    "Sri-Lanka" to listOf("LK", "Шри-Ланка", "LKA", "144"),
    "Liberia" to listOf("LR", "Либерия", "LBR", "430"),
    "Lesotho" to listOf("LS", "Лесото", "LSO", "426"),
    "Lithuania" to listOf("LT", "Литва", "LTU", "440"),
    "Luxembourg" to listOf("LU", "Люксембург", "LUX", "442"),
    "Latvia" to listOf("LV", "Латвия", "LVA", "428"),
    "Libya" to listOf("LY", "Ливия", "LBY", "434"),
    "Morocco" to listOf("MA", "Марокко", "MAR", "504"),
    "Monaco" to listOf("MC", "Монако", "MCO", "492"),
    "Moldova" to listOf("MD", "Молдова", "MDA", "498"),
    "Montenegro" to listOf("ME", "Черногория", "MNE", "499"),
    "Saint Martin" to listOf("MF", "Остров Святого Мартина", "MAF", "663"),
    "Madagascar" to listOf("MG", "Мадагаскар", "MDG", "450"),
    "Marshall-Islands" to listOf("MH", "Маршалловы острова", "MHL", "584"),
    "North-Macedonia" to listOf("MK", "Македония", "MKD", "807"),
    "Mali" to listOf("ML", "Мали", "MLI", "466"),
    "Myanmar" to listOf("MM", "Мьянма", "MMR", "104"),
    "Mongolia" to listOf("MN", "Монголия", "MNG", "496"),
    "Macao" to listOf("MO", "Макао", "MAC", "446"),
    "Northern Mariana Islands" to listOf("MP", "Северные Марианские острова", "MNP", "580"),
    "Martinique" to listOf("MQ", "Мартиника", "MTQ", "474"),
    "Mauritania" to listOf("MR", "Мавритания", "MRT", "478"),
    "Montserrat" to listOf("MS", "Монтсеррат", "MSR", "500"),
    "Malta" to listOf("MT", "Мальта", "MLT", "470"),
    "Mauritius" to listOf("MU", "Маврикий", "MUS", "480"),
    "Maldives" to listOf("MV", "Мальдивы", "MDV", "462"),
    "Malawi" to listOf("MW", "Малави", "MWI", "454"),
    "Mexico" to listOf("MX", "Мексика", "MEX", "484"),
    "Malaysia" to listOf("MY", "Малайзия", "MYS", "458"),
    "Mozambique" to listOf("MZ", "Мозамбик", "MOZ", "508"),
    "Namibia" to listOf("NA", "Намибия", "NAM", "516"),
    "New-Caledonia" to listOf("NC", "Новая Каледония", "NCL", "540"),
    "Niger" to listOf("NE", "Нигер", "NER", "562"),
    "Norfolk Island" to listOf("NF", "Остров Норфолк", "NFK", "574"),
    "Nigeria" to listOf("NG", "Нигерия", "NGA", "566"),
    "Nicaragua" to listOf("NI", "Никарагуа", "NIC", "558"),
    "Nagorno-Karabakh Republic" to listOf("NKR", "Нагорно-Карабахская Республика", null, null),
    "Netherlands" to listOf("NL", "Нидерланды", "NLD", "528"),
    "Norway" to listOf("NO", "Норвегия", "NOR", "578"),
    "Nepal" to listOf("NP", "Непал", "NPL", "524"),
    "Nauru" to listOf("NR", "Науру", "NRU", "520"),
    "Niue" to listOf("NU", "Ниуэ", "NIU", "570"),
    "New-Zealand" to listOf("NZ", "Новая Зеландия", "NZL", "554"),
    "Oman" to listOf("OM", "Оман", "OMN", "512"),
    "Panama" to listOf("PA", "Панама", "PAN", "591"),
    "Peru" to listOf("PE", "Перу", "PER", "604"),
    "French-Polynesia" to listOf("PF", "Французская Полинезия", "PYF", "258"),
    "Papua-New-Guinea" to listOf("PG", "Папуа-Новая Гвинея", "PNG", "598"),
    "Philippines" to listOf("PH", "Филиппины", "PHL", "608"),
    "Pakistan" to listOf("PK", "Пакистан", "PAK", "586"),
    "Poland" to listOf("PL", "Польша", "POL", "616"),
    "Saint-Pierre-Miquelon" to listOf("PM", "Сен-Пьер и Микелон", "SPM", "666"),
    "Pitcairn" to listOf("PN", "Питкерн", "PCN", "612"),
    "Puerto-Rico" to listOf("PR", "Пуэрто-Рико", "PRI", "630"),
    "Palestinian Territory" to listOf("PS", "Палестинская автономия", "PSE", "275"),
    "Portugal" to listOf("PT", "Португалия", "PRT", "620"),
    "Palau" to listOf("PW", "Палау", "PLW", "585"),
    "Paraguay" to listOf("PY", "Парагвай", "PRY", "600"),
    "Qatar" to listOf("QA", "Катар", "QAT", "634"),
    "Reunion" to listOf("RE", "Реюньон", "REU", "638"),
    "Romania" to listOf("RO", "Румыния", "ROM", "642"),
    "Serbia" to listOf("RS", "Сербия", "SRB", "688"),
    "Russia" to listOf("RU", "Россия", "RUS", "643"),
    "Rwanda" to listOf("RW", "Руанда", "RWA", "646"),
    "Saudi-Arabia" to listOf("SA", "Саудовская Аравия", "SAU", "682"),
    "Solomon-Islands" to listOf("SB", "Соломоновы острова", "SLB", "90"),
    "Seychelles" to listOf("SC", "Сейшелы", "SYC", "690"),
    "South-Sudan" to listOf("SD", "Судан", "SDN", "736"),
    "Sweden" to listOf("SE", "Швеция", "SWE", "752"),
    "Singapore" to listOf("SG", "Сингапур", "SGP", "702"),
    "Saint Helena" to listOf("SH", "Святая Елена", "SHN", "654"),
    "Slovenia" to listOf("SI", "Словения", "SVN", "705"),
    "Svalbard and Jan Mayen" to listOf("SJ", "Шпицберген и Ян Майен", "SJM", "744"),
    "Slovakia" to listOf("SK", "Словакия", "SVK", "703"),
    "Sierra Leone" to listOf("SL", "Сьерра-Леоне", "SLE", "694"),
    "San-Marino" to listOf("SM", "Сан-Марино", "SMR", "674"),
    "Senegal" to listOf("SN", "Сенегал", "SEN", "686"),
    "Somalia" to listOf("SO", "Сомали", "SOM", "706"),
    "Suriname" to listOf("SR", "Суринам", "SUR", "740"),
    "South Sudan" to listOf("SS", "Южный Судан", "SSD", "728"),
    "Sao-Tome-and-Principe" to listOf("ST", "Сан-Томе и Принсипи", "STP", "678"),
    "El-Salvador" to listOf("SV", "Эль-Сальвадор", "SLV", "222"),
    "Syria" to listOf("SY", "Сирийская Арабская Республика", "SYR", "760"),
    "Swaziland" to listOf("SZ", "Свазиленд", "SWZ", "748"),
    "Turks-and-Caicos" to listOf("TC", "Острова Теркс и Кайкос", "TCA", "796"),
    "Chad" to listOf("TD", "Чад", "TCD", "148"),
    "French Southern Territories" to listOf("TF", "Французские Южные территории", "ATF", "260"),
    "Togo" to listOf("TG", "Того", "TGO", "768"),
    "Thailand" to listOf("TH", "Таиланд", "THA", "764"),
    "Tajikistan" to listOf("TJ", "Таджикистан", "TJK", "762"),
    "Tokelau" to listOf("TK", "Токелау", "TKL", "772"),
    "Timor-Leste" to listOf("TL", "Тимор-Лесте", "TLS", "626"),
    "Turkmenistan" to listOf("TM", "Туркмения", "TKM", "795"),
    "Tunisia" to listOf("TN", "Тунис", "TUN", "788"),
    "Tonga" to listOf("TO", "Тонга", "TON", "776"),
    "Turkey" to listOf("TR", "Турция", "TUR", "792"),
    "Trinidad-and-Tobago" to listOf("TT", "Тринидад и Тобаго", "TTO", "780"),
    "Tuvalu" to listOf("TV", "Тувалу", "TUV", "798"),
    "Taiwan" to listOf("TW", "Тайвань", "TWN", "158"),
    "Tanzania" to listOf("TZ", "Танзания", "TZA", "834"),
    "Ukraine" to listOf("UA", "Украина", "UKR", "804"),
    "Uganda" to listOf("UG", "Уганда", "UGA", "800"),
    "United States Minor Outlying Islands" to listOf("UM", "Малые Тихоокеанские отдаленные острова Соединенных Штатов", "UMI", "581"),
    "USA" to listOf("US", "США", "USA", "840"),
    "Uruguay" to listOf("UY", "Уругвай", "URY", "858"),
    "Uzbekistan" to listOf("UZ", "Узбекистан", "UZB", "860"),
    "Vatican-City" to listOf("VA", "Папский Престол (Ватикан)", "VAT", "336"),
    "St-Vincent-Grenadines" to listOf("VC", "Сент-Винсент и Гренадины", "VCT", "670"),
    "Venezuela" to listOf("VE", "Венесуэла", "VEN", "862"),
    "British-Virgin-Islands" to listOf("VG", "Виргинские острова (Британские)", "VGB", "92"),
    "US-Virgin-Islands" to listOf("VI", "Виргинские острова (США)", "VIR", "850"),
    "Vietnam" to listOf("VN", "Вьетнам", "VNM", "704"),
    "Vanuatu" to listOf("VU", "Вануату", "VUT", "548"),
    "Wallis-and-Futuna" to listOf("WF", "Уоллис и Футуна", "WLF", "876"),
    "Samoa" to listOf("WS", "Самоа", "WSM", "882"),
    "Yemen" to listOf("YE", "Йемен", "YEM", "887"),
    "Mayotte" to listOf("YT", "Майотта", "MYT", "175"),
    "South-Africa" to listOf("ZA", "Южная Африка", "ZAF", "710"),
    "Zambia" to listOf("ZM", "Замбия", "ZMB", "894"),
    "Zimbabwe" to listOf("ZW", "Зимбабве", "ZWE", "716")


    )

}